### ISSUE TITLE
Errors with DI Tests in Akka.NET 1.1 w/ Unity

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.DI.Unity#4]
<details>
<summary>

DI TestKit might be checking for the wrong type potentially</summary>

 UnityDependencyResolverSpec.DependencyResolver_should_inject_into_BoundedStash_Actor   

```
Current failure:    refs/heads/dev  #4  No changes  15 Jul 16 21:05
First failure:      refs/heads/dev  #3  Changes (2) 15 Jul 16 21:02
```

System.InvalidCastException : Unable to cast object of type 'Akka.Actor.RepointableActorRef' to type 'Akka.Actor.LocalActorRef'.
   at Akka.DI.TestKit.DiResolverSpec.DependencyResolver_should_inject_into_BoundedStash_Actor()
« Hide stacktrace
 UnityDependencyResolverSpec.DependencyResolver_should_inject_into_UnboundedStash_Actor 

```
Current failure:    refs/heads/dev  #4  No changes  15 Jul 16 21:05
First failure:      refs/heads/dev  #3  Changes (2) 15 Jul 16 21:02
```

System.InvalidCastException : Unable to cast object of type 'Akka.Actor.RepointableActorRef' to type 'Akka.Actor.LocalActorRef'.
   at Akka.DI.TestKit.DiResolverSpec.DependencyResolver_should_inject_into_UnboundedStash_Actor()
« Hide stacktrace
 UnityDependencyResolverSpec.DependencyResolver_should_inject_into_normal_mailbox_Actor 

```
Current failure:    refs/heads/dev  #4  No changes  15 Jul 16 21:05
First failure:      refs/heads/dev  #3  Changes (2) 15 Jul 16 21:02
```

System.InvalidCastException : Unable to cast object of type 'Akka.Actor.RepointableActorRef' to type 'Akka.Actor.LocalActorRef'.
   at Akka.DI.TestKit.DiResolverSpec.DependencyResolver_should_inject_into_normal_mailbox_Actor()
</details>

**Comment by derwasp** [comment]
Hey @Aaronontheweb, is this still the issue? It looks like the 1.1.1 is out now.

**Comment by Danthar** [comment]
Solved and updated via PR
